library(dplyr)
library(tidyr)

## run_analysis.R

## This script takes as input the Samsung Galaxy S smartphone
## data generated by the "Human Activity Recognition Uing 
## Smartphones".  It was downloaded as a zip data set using this link:
## https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

## The unzipped files are used in this script.  Detailed desctiptions are provided 
## in the acccompanying codebook, Codebook.md.

## The script requires that the unzipped files be contained in the working directory.
## The script is organized by the 5 steps specified in the project requirements. 

## Step 1: Merge the training and test sets

## Read the pertinent Samsung exercise datasets.

x_train <- read.table("train/X_train.txt")
y_train <- read.table("train/y_train.txt")
subject_train <- read.table("train/subject_train.txt")

x_test <- read.table("test/X_test.txt")
y_test <- read.table("test/y_test.txt")
subject_test <- read.table("test/subject_test.txt")

features <- read.table("features.txt",stringsAsFactors=FALSE)
activity_labels <- read.table("activity_labels.txt")


## The 10299 observations of 561 variables were divided into training and test sets,
## containing 7352 and 2947 observations respectively.  First, merge these
## into a single observations data frame containing all 10299 observations.

observations <- rbind(x_train, x_test)
observations <- tbl_df(observations)
print("step 1 complete")

## Step 2: Extract obnly the measurements on the mean and standard ddeviation for each measurement

## The features table contains list of names for each of the 561 features 
## that were captured during each experimental observation.  Only feature with both mean and
## standard deviations were extracted.  These included features that included
## mean() or std() in their names.  This yielded 66 of the 561 feature columns.

## set value=FALSE to extract the column numbers of the features to extract
mean_std_features_select <- grep("(mean|std)\\(",features$V2,value=FALSE)

## set value=TRUE to extract the names of the features we intend to retain
mean_std_features_names <- grep("(mean|std)\\(",features$V2,value=TRUE)

# Use the mean_std_features_select vector to subset the full observations table
# to just the desired set of columns

observations_mean_std <- observations[, mean_std_features_select]

## Apply the selected feature names to the extracted column vaeriables 
## as a starting point for providing more descriptive labels

names(observations_mean_std) <- mean_std_features_names

print("step 2 complete")

## Step 3: Use descriptive activity names to name the activities in the data set 

## The y data refers to each observational row, while the x data
## each column.  The y data allows us to link a specific activity 
## to each experimental observation row.  To begin, we must meerge the y_train and y_test data 
## into a single data frame. 

## merge the y train and test data sets

activity_linkage <- rbind(y_train,y_test)

## Use the dplyr package to make activity_linkage and activity_names
## table data frames to allow the use of join to combine them into
## one table based on the activity code in the linkage table


activity_linkage <- tbl_df(activity_linkage)
activity_labels <- tbl_df(activity_labels)

## We can now take the activity labels and create a table of the activity
## being measured in each obserrvation trial. The resulting table, 
## observation_activity, has 10299 rows, equal to the number of 
## observational trials. It contains two variables, activity code and activity
## name.

observation_activity <- full_join(activity_linkage,activity_labels,by = "V1")

## Provide descriptive names to each column in observation activity

names(observation_activity) <- c("activitycode","activityname")
## We now need to merge subjects with the activities being monitored in eacb row of the observtional data. First,
## we need to merge the subject training and testing data sets back into a single subjects data frame.

subjects <- rbind(subject_train, subject_test)
names(subjects) <- "subject"

## we can now add the subjects and observation_activity columns
## to the leftmost side of the observationss_mean_std table.  This reconstructs the full set of 
## experimental observation data.  We will now have for each row, the measurements from one trial
## of one subject performing one activity.

observations_mean_std <- bind_cols(observation_activity,observations_mean_std)
observations_mean_std <- bind_cols(subjects,observations_mean_std)

##@ Step 4: Appropriately label the data set with descriptive variable names

## Earlier we provided approprided appropriate labels for subjects ana activities.  
## We initially used the feature.txt file names to name the mean and standard deviation 
## variables.  

## As a next step we will use make.names to transform the original feature.txt 
## names to syntactically valid names. Help for makes.names says that a 
## syantactically valid name:
##      consists of letters, numbers and the dot or underline characters
##      and starts with a letter or the dot not followed by a number...
## All invalid characters are translated to "."

names(observations_mean_std) <- make.names(names(observations_mean_std),unique=T)

## make.names has generated some names wih multiple periods
## where invalid characters were removed. We want to
## limit these to a single "." using sub().

## get thbe names to work with
validnames <- names(observations_mean_std)

## makes.names left a ... pattern within the namne for some features and a .. pattern at
## end for the remainder.

## replace the ... pattern with a single .
validnames <- sub("\\.\\.\\.",".",validnames)

## replacew the .. pattern at the end with a blank
validnames <- sub("\\.\\.","",validnames)

## replace the current names with the cleaned up names

names(observations_mean_std) <- validnames

print("step 4 completed")

## Step 5:  From the data set in step 4, create a seconsd, independent tidy data set with the average of each
## variable for each activty and each subject

## first we create a sata frame grouped by subject and activity name
sub_act_feature <- group_by(observations_mean_std,subject,activityname)

## we then take summarize the grouped table taking the average of each subject activty grouping
sub_act_feature_avgs <- summarise_each(sub_act_feature,funs(mean))

## finally we order the resulting table by actiity within subject, generating tyhe final 
## tidy table

sub_act_feature_avgs <- sub_act_feature_avgs[order(sub_act_feature_avgs$subject,sub_act_feature_avgs$activitycode),]
## we return the final tidy data set

write.table(sub_act_feature_avgs, "sub_act_feature_avgs.txt", row.name=FALSE)

print("step 5 completed")
